package com.gly091020.CreateTreadmill.config;

import net.createmod.catnip.config.ConfigBase;
import org.jetbrains.annotations.NotNull;

public class TreadmillConfig extends ConfigBase {
    public final ConfigInt TREADMILL_STRESS = i(32, 0, "Treadmill Stress", "Set the stress generated by the treadmill");
    public final ConfigInt MAID_MAGNIFICATION = i(16, 0, "Maid Stress Magnification", "The stress increase multiplier from maid affection");
    public final ConfigInt TREADMILL_BASE_SPEED = i(32, 0, "Treadmill Base Speed", "Set the base speed of the treadmill");
    public final ConfigBool TREADMILL_DROP_IT = b(true, "Treadmill Toss", "Whether the treadmill can throw off entities (when powered in reverse)");
    public final ConfigBool TREADMILL_BREAK = b(true, "Entity Escape", "Whether entities on the treadmill can break free");
    public final ConfigBool TREADMILL_SPEED_UP = b(true, "Treadmill Boost", "Whether attacking entities on the treadmill speeds it up");
    @Override
    public @NotNull String getName() {
        return "treadmill";
    }
}
